language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=3.6.1 WP_MULTISITE=0
  - WP_VERSION=3.6.1 WP_MULTISITE=1

matrix:
  exclude:
    - php: 5.5
      env: WP_VERSION=3.6.1
    - php: 5.6
      env: WP_VERSION=3.6.1

install:
  - composer install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test travis ''  localhost $WP_VERSION

script: phpunit
